GET http://localhost:8080/api/salaries
Accept: application/json

###

GET http://localhost:8080/api/salaries/1
Accept: application/json

###

POST http://localhost:8080/api/salaries
Content-Type: application/json
Accept: application/json

{
  "salaryAmount": 802000.00,
  "month": "2024-09-01"
}

###

PUT http://localhost:8080/api/salaries/1
Content-Type: application/json
Accept: application/json

{
  "salaryAmount": 5500.00,
  "month": "2024-08-01"
}

###

DELETE http://localhost:8080/api/salaries/1
Accept: application/json
